const domElements = {
  elementToTranslate: document.querySelectorAll('[data-i18n]'),
  searchInput: document.getElementById('searchInput'),
  changeLanguageButton: document.getElementById('languageButton'),
  languageButton: document.querySelectorAll('.dropdown-item'),
  locationElements: document.querySelectorAll('.location'),
  day: document.getElementById('date'),
  temperatureElements: document.getElementsByClassName('temperature'),
  latitude: document.getElementById('latitude'),
  longitude: document.getElementById('longitude'),
  currentTemperature: document.getElementById('temperature'),
  weatherText: document.getElementById('text'),
  feelslike: document.getElementById('feelslike'),
  wind: document.getElementById('wind'),
  humidity: document.getElementById('humidity'),
  region: document.getElementById('region'),
  country: document.getElementById('country'),
  name: document.getElementById('name'),
  weatherForDay1: document.getElementById('weatherForDay1'),
  weatherForDay2: document.getElementById('weatherForDay2'),
  weatherForDay3: document.getElementById('weatherForDay3'),
  currentWeatherIcon: document.getElementById('weather-icon'),
  weatherIcon1: document.getElementById('weather-icon1'),
  weatherIcon2: document.getElementById('weather-icon2'),
  weatherIcon3: document.getElementById('weather-icon3'),
  time: document.getElementById('time'),
  day1: document.getElementById('day1'),
  day2: document.getElementById('day2'),
  day3: document.getElementById('day3'),
  searchForm: document.getElementById('searchForm'),
  microphone: document.getElementById('microphone'),
};

export default domElements;
